# Namespace configuration
watchAnyNamespace: true

# Image configuration
# Use specific version tag instead of latest for production stability
image:
  registry: quay.io
  repository: strimzi
  name: operator
  tag: 0.46.0  # Specify exact version

# Security context settings
podSecurityContext:
  fsGroup: null
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsNonRoot: true

# Production resource requirements
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# High availability settings
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - strimzi-cluster-operator
          topologyKey: "kubernetes.io/hostname"

# Production-specific settings
logLevel: INFO
logFormat: json