# Namespace configuration
watchNamespaces: ["strimzi-lab"]

# Image configuration
# Use specific version tag instead of latest for production stability
image:
  registry: quay.io
  repository: strimzi
  name: operator
  tag: 0.46.0  # Specify exact version

# OpenShift security context
podSecurityContext:
  fsGroup: null
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

# Resource limits for development
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Development-specific settings
logLevel: DEBUG